<table>
    <tr>
        <th>Name</th><th>Options</th>
    </tr>
    <?php foreach ($this->entries as $entry): ?>
    <tr>
        <td><p id="name-<?php echo $this->escape($entry->id) ?>"><?php echo $this->escape($entry->name) ?></p></td>
        <td>
            <noscript>
                <form action="/addressbook/rename/id/<?php echo $this->escape($entry->id) ?>" method="get">
                    <p>
                        <input type="submit" value="Rename" />
                    </p>
                </form>
            </noscript>
            <form action="/addressbook/delete" method="post" class="delete">
                <p>
                    <input type="hidden" name="id" value="<?php echo $this->escape($entry->id) ?>" />
                    <input type="submit" value="Delete" />
                </p>
            </form>
        </td>
    </tr>

    <?php endforeach ?>
</table>

<p><a href="/addressbook/add">New Address Book</a></p>

<script type="text/javascript">
    //<![CDATA[
    <?php foreach ($this->entries as $entry): ?>
        new Ajax.InPlaceEditor('name-<?php echo $this->escape($entry->id) ?>', '/addressbook/rename',
        {
            callback: function(form, value) { return 'name=' + encodeURIComponent(value) + '&id=' + encodeURIComponent(<?php echo $this->escape($entry->id) ?>) }
        });
    <?php endforeach ?>

    $$('form.delete').each(function(element)
    {
        Event.observe(element, 'submit', function(event)
        {
            var check = confirm("Delete address book and all contacts?");

            if(!check)
            {
                event.stop();
            }
        });
    });
    //]]>
</script>