<div id="addressBookSelector">
    <?php
    $this->form->setAction($this->url());
    $this->form->setAttrib('class', 'inline');
    echo $this->form;
    ?>
</div>

<div id="contacts">
    <?php foreach ($this->contacts as $contact): ?>
    <div class="contact">
        <span class="name">
            <a href="contact/view/id/<?php echo $contact->id ?>">
                <?php echo $this->escape($contact->firstName) ?>
                <?php echo $this->escape($contact->lastName) ?>
            </a>
        </span>
        <span class="email">Email:
            <a href="mailto:<?php echo $this->escape($contact->email) ?>">
                <?php echo $this->escape($contact->email) ?></a>
        </span>
        <span class="homeTel">Home: <?php echo $this->escape($contact->homeTel) ?></span>
        <span class="workTel">Work: <?php echo $this->escape($contact->workTel) ?></span>
        <span class="mobileTel">Mobile: <?php echo $this->escape($contact->mobileTel) ?></span>
        <span class="fax">Fax: <?php echo $this->escape($contact->fax) ?></span>
    </div>
    <?php endforeach ?>
</div>

<script type="text/javascript">
    //<![CDATA[
    Event.observe('addressbook', 'change', function()
    {
        $('address_book_form').submit();
    });
    //]]>
</script>