<div id="addressBookSelector">
    <?php
    $this->form->setAction($this->url());
    $this->form->setAttrib('class', 'inline');
    echo $this->form;
    ?>
</div>

<div id="contacts">
    <?php foreach ($this->contacts as $contact): ?>
    <a href="contact/view/id/<?php echo $contact->id ?>" class="contact">
        <span class="name">
                <?php echo $this->escape($contact->firstName) ?>
                <?php echo $this->escape($contact->lastName) ?>
        </span>
        <span class="homeTel"><?php echo $this->escape($contact->homeTel) ?></span>
        <span class="workTel"><?php echo $this->escape($contact->workTel) ?></span>
        <span class="mobileTel"><?php echo $this->escape($contact->mobileTel) ?></span>
    </a>
    <?php endforeach ?>
</div>

<script type="text/javascript">
    //<![CDATA[
    Event.observe('addressbook', 'change', function()
    {
        $('address_book_form').submit();
    });
    //]]>
</script>