<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head profile="http://www.w3.org/2005/10/profile">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php $this->headTitle('Address Book'); ?>
        <?php $this->headTitle()->setSeparator(' / '); ?>
        <?php echo $this->headTitle(); ?>
        <?php $this->headLink()->appendStylesheet('/css/blueprint/screen.css', 'screen, projection'); ?>
        <?php $this->headLink()->appendStylesheet('/css/blueprint/print.css', 'print'); ?>
        <?php $this->headLink()->appendStylesheet('/css/blueprint/ie.css', 'screen, projection', 'lt IE 8'); ?>
        <?php $this->headLink()->appendStylesheet('/css/main.css', 'screen, projection'); ?>
        <?php $this->headLink()->appendStylesheet('/css/ie.css', 'screen, projection', 'IE'); ?>
        <?php $this->headScript()->appendFile('/js/prototype.js'); ?>
        <?php $this->headScript()->appendFile('/js/scriptaculous.js'); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="container" class="container">
            <div id="header" class="span-24 last">
                <h1>Address Book</h1>
            </div>
            <div id="navigation" class="span-24 last">
                <a href="<?php echo $this->url(
                array('controller'=>'index'),
                   'default', true) ?>">View Contacts</a>
                <a href="<?php echo $this->url(
                array('controller'=>'addressbook'),
                   'default', true) ?>">View Address Books</a>
                <a href="<?php echo $this->url(
                array('controller'=>'contact', 'action' => 'add'),
                   'default', true) ?>">Add Contact</a>
            </div>
            <div id="content" class="span-24 last">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="footer" class="span-24 last">
                <p>Icons by <a href="http://www.famfamfam.com/lab/icons/silk/">FamFamFam</a></p>
            </div>
        </div>
    </body>
</html>